/-
Copyright (c) 2026 Monica Omar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Monica Omar
-/

import LeanPool.Monlib4.LinearAlgebra.Ips.MinimalProj
import LeanPool.Monlib4.LinearAlgebra.TensorProduct.OrthonormalBasis
import Mathlib.LinearAlgebra.TensorProduct.Finiteness
import LeanPool.Monlib4.LinearAlgebra.QuantumSet.SchurMul
import Mathlib.LinearAlgebra.TensorProduct.RightExactness
import LeanPool.Monlib4.LinearAlgebra.PiDirectSum
import LeanPool.Monlib4.LinearAlgebra.Matrix.Reshape

/-!
# LeanPool.Monlib4.LinearAlgebra.TensorProduct.Submodule

Imported Lean Pool material for `LeanPool.Monlib4.LinearAlgebra.TensorProduct.Submodule`.
-/

open scoped TensorProduct

/-- The submodule of a tensor product generated by tensors from two submodules. -/
noncomputable def Submodule.tensorProduct {R : Type*} {E F : Type*} [CommSemiring R]
  [AddCommMonoid E] [AddCommMonoid F] [Module R E] [Module R F]
  (V : Submodule R E) (W : Submodule R F) :
    Submodule R (E ⊗[R] F) :=
LinearMap.range (TensorProduct.mapIncl V W : V ⊗[R] W →ₗ[R] E ⊗[R] F)

theorem Submodule.tensorProduct_mem {R : Type*} {E F : Type*} [CommSemiring R]
  [AddCommMonoid E] [AddCommMonoid F] [Module R E] [Module R F]
  {V : Submodule R E} {W : Submodule R F} (x : V ⊗[R] W) :
  (TensorProduct.mapIncl V W) x ∈ V.tensorProduct W :=
⟨_, rfl⟩

/-- Choose a preimage of an element of `V.tensorProduct W` in `V ⊗ W`. -/
noncomputable def Submodule.memTensorProduct {R : Type*} {E F : Type*} [CommSemiring R]
  [AddCommMonoid E] [AddCommMonoid F] [Module R E] [Module R F]
  {V : Submodule R E} {W : Submodule R F} (vw : V.tensorProduct W) :
  V ⊗[R] W :=
vw.property.choose
theorem Submodule.memTensorProduct_eq {R : Type*} {E F : Type*} [CommSemiring R]
  [AddCommMonoid E] [AddCommMonoid F] [Module R E] [Module R F]
  {V : Submodule R E} {W : Submodule R F} (vw : V.tensorProduct W) :
  (TensorProduct.mapIncl V W) (memTensorProduct vw) = vw :=
Set.apply_rangeSplitting (fun x ↦ (TensorProduct.mapIncl V W) x) vw

theorem TensorProduct.mapIncl_isInjective {R : Type*} {E F : Type*} [RCLike R]
  [NormedAddCommGroup E] [NormedAddCommGroup F] [InnerProductSpace R E] [InnerProductSpace R F]
  [FiniteDimensional R E] [FiniteDimensional R F]
  {V : Submodule R E} {W : Submodule R F} :
  Function.Injective (TensorProduct.mapIncl V W : V ⊗[R] W → E ⊗[R] F) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  obtain ⟨x, rfl⟩ := TensorProduct.exists_finset a
  simp only [TensorProduct.mapIncl, map_tmul, map_sum, Submodule.coe_subtype] at ha ⊢
  rw [TensorProduct.inner_ext_iff'] at ha ⊢
  intro v w
  specialize ha (↑v) (↑w)
  simp_rw [inner_zero_left, sum_inner, TensorProduct.inner_tmul,
    Submodule.coe_inner] at ha ⊢
  exact ha

theorem Submodule.mapIncl_memTensorProduct {R : Type*} {E F : Type*} [RCLike R]
  [NormedAddCommGroup E] [NormedAddCommGroup F] [InnerProductSpace R E] [InnerProductSpace R F]
  [FiniteDimensional R E] [FiniteDimensional R F]
  {V : Submodule R E} {W : Submodule R F} (v : V ⊗[R] W) :
  Submodule.memTensorProduct (⟨_, Submodule.tensorProduct_mem v⟩ : V.tensorProduct W) = v := by
  apply_fun (TensorProduct.mapIncl V W) using TensorProduct.mapIncl_isInjective
  rw [Submodule.memTensorProduct_eq]

variable {𝕜 E F : Type*} [RCLike 𝕜] [NormedAddCommGroup E]
  [NormedAddCommGroup F] [InnerProductSpace 𝕜 E] [InnerProductSpace 𝕜 F]
variable [FiniteDimensional 𝕜 E] [FiniteDimensional 𝕜 F]

theorem norm_tmul {𝕜 B C : Type*} [RCLike 𝕜] [NormedAddCommGroup B]
    [NormedAddCommGroup C] [InnerProductSpace 𝕜 B] [InnerProductSpace 𝕜 C] [FiniteDimensional 𝕜 B]
    [FiniteDimensional 𝕜 C] (x : B) (y : C) : ‖x ⊗ₜ[𝕜] y‖ = ‖x‖ * ‖y‖ := by
  symm
  calc
    ‖x‖ * ‖y‖ = Real.sqrt (RCLike.re (inner 𝕜 x x)) * Real.sqrt (RCLike.re (inner 𝕜 y y)) := by
      simp_rw [@norm_eq_sqrt_re_inner 𝕜]
    _ = Real.sqrt (RCLike.re (inner 𝕜 x x) * RCLike.re (inner 𝕜 y y)) := by
      rw [Real.sqrt_mul inner_self_nonneg]
    _ = Real.sqrt (RCLike.re ((inner 𝕜 x x) * (inner 𝕜 y y))) := by
      congr 1
      simp only [RCLike.mul_re, @inner_self_im 𝕜, MulZeroClass.zero_mul, sub_zero]
    _ = Real.sqrt (RCLike.re (inner 𝕜 (x ⊗ₜ[𝕜] y) (x ⊗ₜ[𝕜] y))) := by
      rw [TensorProduct.inner_tmul]
    _ = ‖x ⊗ₜ[𝕜] y‖ := by rw [@norm_eq_sqrt_re_inner 𝕜]

open scoped InnerProductSpace
omit [FiniteDimensional 𝕜 E] [FiniteDimensional 𝕜 F] in
lemma TensorProduct.mapIncl_norm_map (V : Submodule 𝕜 E) (W : Submodule 𝕜 F) (x : V ⊗[𝕜] W) :
  ‖TensorProduct.mapIncl V W x‖ = ‖x‖ := by
  obtain ⟨S, rfl⟩ := TensorProduct.exists_finset x
  simp only [TensorProduct.mapIncl, map_sum, TensorProduct.map_tmul, Submodule.coe_subtype]
  simp_rw [@norm_eq_sqrt_re_inner 𝕜]
  congr 2
  simp only [sum_inner, inner_sum, TensorProduct.inner_tmul, ← Submodule.coe_inner]

/-- The natural linear isometry between `V ⊗ W` and its image in `E ⊗ F`. -/
noncomputable def Submodule.tensorProductLinearIsometryEquiv
  (V : Submodule 𝕜 E) (W : Submodule 𝕜 F) :
    (V ⊗[𝕜] W) ≃ₗᵢ[𝕜] (V.tensorProduct W) where
  toFun x := ⟨(TensorProduct.mapIncl V W) x, ⟨_, rfl⟩⟩
  invFun x := Submodule.memTensorProduct x
  left_inv x := by simp only [Submodule.mapIncl_memTensorProduct]
  right_inv x := SetCoe.ext (Submodule.memTensorProduct_eq x)
  map_add' _ _ := by
    simp only [TensorProduct.mapIncl, map_add]; rfl
  map_smul' _ _ := by
    apply SetCoe.ext
    simp
  norm_map' x := TensorProduct.mapIncl_norm_map _ _ _

/-- The tensor product orthonormal basis, transported to `V.tensorProduct W`. -/
noncomputable def Submodule.tensorProductOrthonormalBasis {V : Submodule 𝕜 E} {W : Submodule 𝕜 F}
  {ι₁ ι₂ : Type*} [Fintype ι₁] [Fintype ι₂]
  (v : OrthonormalBasis ι₁ 𝕜 V) (w : OrthonormalBasis ι₂ 𝕜 W) :
  OrthonormalBasis (ι₁ × ι₂) 𝕜 (V.tensorProduct W) :=
OrthonormalBasis.map (v.tensorProduct w) (Submodule.tensorProductLinearIsometryEquiv V W)

theorem Submodule.tensorProductOrthonormalBasis_apply {V : Submodule 𝕜 E} {W : Submodule 𝕜 F}
  {ι₁ ι₂ : Type*} [Fintype ι₁] [Fintype ι₂]
  (v : OrthonormalBasis ι₁ 𝕜 V) (w : OrthonormalBasis ι₂ 𝕜 W) (i : ι₁ × ι₂) :
  Submodule.tensorProductOrthonormalBasis v w i =
    (v i.1).val ⊗ₜ[𝕜] (w i.2).val := by
  simp only [Submodule.tensorProductOrthonormalBasis, OrthonormalBasis.map_apply]
  simp only [OrthonormalBasis.tensorProduct_apply']
  rfl

theorem Submodule.tensorProduct_finrank {V : Submodule 𝕜 E} {W : Submodule 𝕜 F} :
  Module.finrank 𝕜 (V.tensorProduct W) = Module.finrank 𝕜 V * Module.finrank 𝕜 W := by
  simp only [← Module.finrank_tensorProduct]
  exact Eq.symm (LinearEquiv.finrank_eq
    (Submodule.tensorProductLinearIsometryEquiv V W).toLinearEquiv)

omit [FiniteDimensional 𝕜 E] [FiniteDimensional 𝕜 F] in
theorem rankOne_tmul {x₁ y₁ : E} {x₂ y₂ : F} :
  (rankOne 𝕜 (x₁ ⊗ₜ[𝕜] x₂) (y₁ ⊗ₜ[𝕜] y₂)).toLinearMap =
    TensorProduct.map (rankOne 𝕜 x₁ y₁).toLinearMap (rankOne 𝕜 x₂ y₂).toLinearMap := by
  ext a b
  simp [TensorProduct.inner_tmul, TensorProduct.smul_tmul', smul_smul, mul_comm]

theorem orthogonalProjection_map_orthogonalProjection (V : Submodule 𝕜 E) (W : Submodule 𝕜 F) :
  TensorProduct.map
  (orthogonalProjection' V).toLinearMap (orthogonalProjection' W).toLinearMap =
  orthogonalProjection' (V.tensorProduct W) := by
  let v := stdOrthonormalBasis 𝕜 V
  let w := stdOrthonormalBasis 𝕜 W
  rw [OrthonormalBasis.orthogonalProjection'_eq_sum_rankOne
    (Submodule.tensorProductOrthonormalBasis v w),
    OrthonormalBasis.orthogonalProjection'_eq_sum_rankOne v,
    OrthonormalBasis.orthogonalProjection'_eq_sum_rankOne w]
  simp_rw [ContinuousLinearMap.toLinearMap_sum, TensorProduct.sum_map, TensorProduct.map_sum,
    ← rankOne_tmul, Submodule.tensorProductOrthonormalBasis_apply]
  rw [← Finset.sum_product']
  simp only [Finset.univ_product_univ]

theorem TensorProduct.submodule_exists_le_tensorProduct {R M N : Type*}
  [Field R] [AddCommGroup M] [AddCommGroup N] [Module R M] [Module R N]
  (U : Submodule R (M ⊗[R] N)) (hU : Module.Finite R ↥U) :
  ∃ (M' : Submodule R M) (N' : Submodule R N)
    (_ : Module.Finite R ↥M') (_ : Module.Finite R ↥N'),
  U ≤ M'.tensorProduct N' := by
  let e := Module.Basis.ofVectorSpace R U
  let e'' : Set U.carrier := (Set.range e)
  let e''' : Set U := e''
  let e' : Set (M ⊗[R] N) := e''
  let he' : e'.Finite := Set.toFinite e'
  obtain ⟨M', N', hM', hN', hS⟩ :=
    TensorProduct.exists_finite_submodule_of_setFinite e' he'
  have : Submodule.span R e''' = ⊤ := e.span_eq
  have : Submodule.span R e' = U := by
    simp only [e']
    calc Submodule.span R (Subtype.val '' e'')
        = Submodule.map (U.subtype) (Submodule.span R e''') := ?_
      _ = Submodule.map (U.subtype) (⊤ : Submodule R ↥U) := by rw [this]
      _ = U := by simp only [Submodule.map_top, Submodule.range_subtype]
    rw [← Submodule.span_image]
    rfl
  have :=
    calc U = Submodule.span R e' := this.symm
        _ ≤ Submodule.span R (LinearMap.range (TensorProduct.mapIncl M' N')) :=
          Submodule.span_mono hS
  use M', N', hM', hN'
  simp_all only [TensorProduct.mapIncl,
    Submodule.span_coe_eq_restrictScalars, Submodule.restrictScalars_self]
  exact this

theorem orthogonalProjection'_ortho_eq {𝕜 E : Type*} [RCLike 𝕜]
  [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] (K : Submodule 𝕜 E)
  [K.HasOrthogonalProjection] :
  orthogonalProjection' Kᗮ = ContinuousLinearMap.id 𝕜 _ - orthogonalProjection' K := by
  calc
    orthogonalProjection' Kᗮ = Kᗮ.starProjection := rfl
    _ = ContinuousLinearMap.id 𝕜 E - K.starProjection := by
      rw [Submodule.id_eq_sum_starProjection_self_orthogonalComplement (K := K)]
      abel
    _ = ContinuousLinearMap.id 𝕜 E - orthogonalProjection' K := rfl

theorem TensorProduct.submodule_exists_le_tensorProduct_ofFiniteDimensional
  {R M N : Type*}
  [Field R] [AddCommGroup M] [AddCommGroup N] [Module R M] [Module R N]
  [Module.Finite R M] [Module.Finite R N]
  (U : Submodule R (M ⊗[R] N)) :
  ∃ (M' : Submodule R M) (N' : Submodule R N),
  U ≤ M'.tensorProduct N' := by
  obtain ⟨V, W, _, _, hVW⟩ := TensorProduct.submodule_exists_le_tensorProduct U
    (FiniteDimensional.finiteDimensional_submodule U)
  exact ⟨V, W, hVW⟩

theorem orthogonalProjection_of_tensorProduct {E F : Type*}
  [NormedAddCommGroup E] [NormedAddCommGroup F] [InnerProductSpace ℂ E]
  [InnerProductSpace ℂ F] [FiniteDimensional ℂ E] [FiniteDimensional ℂ F]
  {A : E ⊗[ℂ] F →ₗ[ℂ] E ⊗[ℂ] F}
  (hA : ∃ (U : Submodule ℂ E) (V : Submodule ℂ F),
    (orthogonalProjection' (U.tensorProduct V)).toLinearMap = A) :
  ∃ (U : Submodule ℂ (E ⊗[ℂ] F)), (orthogonalProjection' U).toLinearMap = A := by
  obtain ⟨U, V, hUV⟩ := hA
  exact ⟨U.tensorProduct V, hUV⟩

local notation x" ⊗ₘ "y => TensorProduct.map x y

open Matrix

/-- Identify functions on `n × Unit` with functions on `n`. -/
def piProdUnitEquivPi {R n : Type*} [Semiring R] : (n × Unit → R) ≃ₗ[R] n → R
    where
  toFun x i := x (i, PUnit.unit)
  invFun x i := x i.1
  left_inv x := by
    ext; simp
  right_inv x := by ext1; rfl
  map_add' x y := by simp only [Pi.add_apply]; rfl
  map_smul' r x := by simp only [RingHom.id_apply]; rfl

/-- `matrix.replicateCol` written as a linear equivalence -/
def Matrix.ofReplicateCol {R n : Type*} [Semiring R] : Matrix n Unit R ≃ₗ[R] n → R :=
  (reshape : Matrix n Unit R ≃ₗ[R] n × Unit → R).trans piProdUnitEquivPi

/-- Remove a trailing `Unit` factor from the column index of a matrix. -/
def matrixProdUnitRight {R n m : Type*} [Semiring R] : Matrix n (m × Unit) R ≃ₗ[R] Matrix n m R
    where
  toFun x i j := x i (j, PUnit.unit)
  invFun x i j := x i j.1
  left_inv x := by
    ext; simp
  right_inv x := by ext1; rfl
  map_add' x y := by rfl
  map_smul' r x := by simp only [RingHom.id_apply]; rfl

open Kronecker
/-- `vec_mulVec x y` written as a kronecker product -/
theorem replicateCol_hMul_replicateCol_conjTranspose_is_kronecker_of_vectors
    {R m n : Type*} [Semiring R]
    (x : m → R) (y : n → R) :
    vecMulVec x y =
      reshape.symm
        (Matrix.ofReplicateCol
          (matrixProdUnitRight (replicateCol Unit x ⊗ₖ replicateCol Unit y))) := by
  ext
  simp_rw [reshape_symm_apply, Matrix.ofReplicateCol, matrixProdUnitRight, piProdUnitEquivPi,
    LinearEquiv.trans_apply, LinearEquiv.coe_mk]
  simp only [LinearMap.coe_mk, AddHom.coe_mk, kroneckerMap_apply, replicateCol_apply]
  rw [reshape_apply, vecMulVec_apply]

section

variable {ι₁ ι₂ : Type*} [DecidableEq ι₁] [DecidableEq ι₂] [Fintype ι₁] [Fintype ι₂]
    {M₁ : ι₁ → Type*} {M₂ : ι₂ → Type*}
    [(i₁ : ι₁) → NormedAddCommGroup (M₁ i₁)] [(i₂ : ι₂) → NormedAddCommGroup (M₂ i₂)]
    [(i₁ : ι₁) → InnerProductSpace 𝕜 (M₁ i₁)] [(i₂ : ι₂) → InnerProductSpace 𝕜 (M₂ i₂)]

/-- Tensor products commute with finite `PiLp 2` products as a linear equivalence. -/
@[simps!]
noncomputable def PiLpTensorEquiv :
  (PiLp 2 M₁ ⊗[𝕜] PiLp 2 M₂) ≃ₗ[𝕜]
    PiLp 2 (fun (i : ι₁ × ι₂) => (M₁ i.1) ⊗[𝕜] (M₂ i.2)) :=
((TensorProduct.congr
    (WithLp.linearEquiv 2 𝕜 (∀ i, M₁ i))
    (WithLp.linearEquiv 2 𝕜 (∀ i, M₂ i))).trans directSumTensor).trans
  (WithLp.linearEquiv 2 𝕜 (∀ i : ι₁ × ι₂, M₁ i.1 ⊗[𝕜] M₂ i.2)).symm

theorem PiLpTensorEquiv_tmul (x : PiLp 2 M₁) (y : PiLp 2 M₂) (i : ι₁ × ι₂) :
  PiLpTensorEquiv (x ⊗ₜ y) i = x i.1 ⊗ₜ[𝕜] y i.2 := by
  simp [PiLpTensorEquiv, TensorProduct.congr_tmul, directSumTensor_apply,
    directSumTensorToFun_apply]

variable [(i : ι₁) → FiniteDimensional 𝕜 (M₁ i)]
  [(i : ι₂) → FiniteDimensional 𝕜 (M₂ i)]

omit [(i : ι₁) → FiniteDimensional 𝕜 (M₁ i)]
  [(i : ι₂) → FiniteDimensional 𝕜 (M₂ i)] in
@[simp]
theorem PiLpTensorEquiv_norm_map
  (x : (PiLp 2 M₁ ⊗[𝕜] PiLp 2 M₂)) :
  ‖(PiLpTensorEquiv x : PiLp 2 (fun i : ι₁ × ι₂ => M₁ i.1 ⊗[𝕜] M₂ i.2))‖ = ‖x‖ := by
  simp_rw [norm_eq_sqrt_re_inner (𝕜 := 𝕜)]
  obtain ⟨S, rfl⟩ := TensorProduct.exists_finset x
  simp_rw [map_sum, sum_inner, inner_sum]
  simp_rw [TensorProduct.inner_tmul, PiLp.inner_apply, PiLpTensorEquiv_tmul, Finset.sum_mul,
    Finset.mul_sum, Fintype.sum_prod_type]
  simp only [TensorProduct.inner_tmul]

/-- `PiLpTensorEquiv` as a linear isometry equivalence. -/
@[simps! -isSimp]
noncomputable abbrev PiLpTensorLinearIsometryEquiv :
    (PiLp 2 M₁ ⊗[𝕜] PiLp 2 M₂) ≃ₗᵢ[𝕜]
      PiLp 2 (fun (i : ι₁ × ι₂) => (M₁ i.1) ⊗[𝕜] (M₂ i.2)) where
  toLinearEquiv := PiLpTensorEquiv
  norm_map' := PiLpTensorEquiv_norm_map

omit [(i : ι₁) → FiniteDimensional 𝕜 (M₁ i)]
  [(i : ι₂) → FiniteDimensional 𝕜 (M₂ i)] in
theorem PiLpTensorLinearIsometryEquiv_tmul
    (x : PiLp 2 M₁) (y : PiLp 2 M₂) (i : ι₁ × ι₂) :
  PiLpTensorLinearIsometryEquiv (x ⊗ₜ y) i = x i.1 ⊗ₜ[𝕜] y i.2 :=
PiLpTensorEquiv_tmul x y i

end

/-- Tensor product equivalence for finite Euclidean spaces. -/
noncomputable abbrev euclideanSpaceTensor {R : Type*} [RCLike R] {ι₁ ι₂ : Type*}
  [Fintype ι₁] [Fintype ι₂]
  [DecidableEq ι₁] [DecidableEq ι₂] :
   (EuclideanSpace R ι₁ ⊗[R] EuclideanSpace R ι₂) ≃ₗᵢ[R]
   EuclideanSpace (R ⊗[R] R) (ι₁ × ι₂) :=
PiLpTensorLinearIsometryEquiv

lemma euclideanSpaceTensor_apply {R : Type*} [RCLike R] {ι₁ ι₂ : Type*}
  [Fintype ι₁] [Fintype ι₂]
  [DecidableEq ι₁] [DecidableEq ι₂] (x : EuclideanSpace R ι₁) (y : EuclideanSpace R ι₂)
  (i : ι₁ × ι₂) :
  euclideanSpaceTensor (R := R) (x ⊗ₜ y) i = x i.1 ⊗ₜ y i.2 :=
PiLpTensorLinearIsometryEquiv_tmul x y i

/-- The left unit tensor equivalence as a linear isometry equivalence. -/
@[simps!]
noncomputable def TensorProduct.lidLinearIsometryEquiv
  (𝕜 E : Type*) [RCLike 𝕜] [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
  [FiniteDimensional 𝕜 E] :
    (𝕜 ⊗[𝕜] E) ≃ₗᵢ[𝕜] E where
  toLinearEquiv := TensorProduct.lid _ _
  norm_map' x := by
    rw [norm_eq_sqrt_re_inner (𝕜 := 𝕜)]
    simp only [← LinearEquiv.coe_toLinearMap, ← LinearMap.adjoint_inner_left,
      TensorProduct.lid_adjoint]
    simp only [LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply, ← norm_eq_sqrt_re_inner]

/-- Tensor product equivalence for finite Euclidean spaces, using `R ⊗[R] R ≃ R`. -/
noncomputable abbrev euclideanSpaceTensor' {R : Type*} [RCLike R] {ι₁ ι₂ : Type*}
  [Fintype ι₁] [Fintype ι₂]
  [DecidableEq ι₁] [DecidableEq ι₂] :
   (EuclideanSpace R ι₁ ⊗[R] EuclideanSpace R ι₂) ≃ₗᵢ[R]
   EuclideanSpace R (ι₁ × ι₂) :=
(euclideanSpaceTensor (R := R)).trans
  (LinearIsometryEquiv.piLpCongrRight 2 (fun _ => TensorProduct.lidLinearIsometryEquiv R _))
lemma euclideanSpaceTensor'_apply {R : Type*} [RCLike R] {ι₁ ι₂ : Type*}
  [Fintype ι₁] [Fintype ι₂]
  [DecidableEq ι₁] [DecidableEq ι₂] (x : EuclideanSpace R ι₁) (y : EuclideanSpace R ι₂)
  (i : ι₁ × ι₂) :
  euclideanSpaceTensor' (R := R) (x ⊗ₜ y) i = x i.1 * y i.2 := by
  rw [LinearIsometryEquiv.trans_apply]
  change TensorProduct.lidLinearIsometryEquiv R R
      ((euclideanSpaceTensor (R := R) (x ⊗ₜ[R] y)) i) =
    x i.1 * y i.2
  rw [euclideanSpaceTensor_apply]
  change (TensorProduct.lid R R) (x i.1 ⊗ₜ[R] y i.2) = x i.1 * y i.2
  rw [TensorProduct.lid_tmul]
  rfl

open scoped FiniteDimensional
theorem LinearIsometryEquiv.linearMap_adjoint {f : E ≃ₗᵢ[𝕜] F} :
  LinearMap.adjoint f.toLinearMap = f.symm.toLinearMap := by
  letI := FiniteDimensional.complete 𝕜 E
  letI := FiniteDimensional.complete 𝕜 F
  calc
    LinearMap.adjoint f.toLinearMap =
        ContinuousLinearMap.adjoint
          (LinearIsometry.toContinuousLinearMap f.toLinearIsometry) := rfl
    _ = LinearIsometry.toContinuousLinearMap f.symm.toLinearIsometry := by
      simp only [ContinuousLinearMap.coe_inj]
      exact LinearIsometryEquiv.adjoint_eq_symm _
    _ = f.symm.toLinearMap := rfl

theorem TensorProduct.ring_tmul {R : Type*} [CommRing R] (x : R ⊗[R] R) :
  ∃ (a b : R), x = a ⊗ₜ[R] b := by
  refine ⟨1, TensorProduct.lid R R x, ?_⟩
  rw [← TensorProduct.lid_symm_apply]
  exact (TensorProduct.lid R R).symm_apply_apply x |>.symm

theorem submodule_neq_tensorProduct_of {R : Type*} [RCLike R]
  {E F : Type*} [NormedAddCommGroup E] [NormedAddCommGroup F]
  [InnerProductSpace R E] [InnerProductSpace R F]
  [FiniteDimensional R E] [FiniteDimensional R F]
  (U : Submodule R (E ⊗[R] F))
  {p : ℕ} (hp : Nat.Prime p)
  (hU : Module.finrank R U = p) :
  ¬ ∃ (V : Submodule R E) (W : Submodule R F)
      (_ : 1 < Module.finrank R V)
      (_ : 1 < Module.finrank R W),
      U = V.tensorProduct W := by
  push Not
  intro V W hVW₁ hVW₂ hVW
  have : p = Module.finrank R V * Module.finrank R W := by
    rw [← hU, hVW]; exact Submodule.tensorProduct_finrank
  exact
    (Nat.not_prime_of_mul_eq this.symm (Ne.symm (Nat.ne_of_lt hVW₁)) (Ne.symm (Nat.ne_of_lt hVW₂)))
    hp
